[package]
name = "webkv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.80"
anyhow = "1.0.86"
futures = "0.3.30"
futures-test = "0.3.30"
itertools = "0.13.0"
tracing = "0.1.40"